/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lotusbeautygui;

/**
 *
 * @author Pinto
 */
public class MenuKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form MenuKaryawan
     */
    public MenuKaryawan() {
        initComponents();
        this.setTitle("Menu Karyawan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_karyawan = new javax.swing.JButton();
        jButton_produk = new javax.swing.JButton();
        jButton_pembeli = new javax.swing.JButton();
        jButton_pesanan = new javax.swing.JButton();
        jButton_pengiriman = new javax.swing.JButton();
        jButton_pembayaran = new javax.swing.JButton();
        jLabel_logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 142, 202));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATABASE");

        jButton_karyawan.setText("Data Karyawan");
        jButton_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_karyawanActionPerformed(evt);
            }
        });

        jButton_produk.setText("Data Produk");
        jButton_produk.setPreferredSize(new java.awt.Dimension(108, 23));
        jButton_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produkActionPerformed(evt);
            }
        });

        jButton_pembeli.setText("Data Pembeli");
        jButton_pembeli.setPreferredSize(new java.awt.Dimension(108, 23));
        jButton_pembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pembeliActionPerformed(evt);
            }
        });

        jButton_pesanan.setText("Data Pesanan");
        jButton_pesanan.setPreferredSize(new java.awt.Dimension(108, 23));
        jButton_pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pesananActionPerformed(evt);
            }
        });

        jButton_pengiriman.setText("Data Pengiriman");
        jButton_pengiriman.setMaximumSize(new java.awt.Dimension(120, 23));
        jButton_pengiriman.setMinimumSize(new java.awt.Dimension(120, 23));
        jButton_pengiriman.setPreferredSize(new java.awt.Dimension(108, 23));
        jButton_pengiriman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pengirimanActionPerformed(evt);
            }
        });

        jButton_pembayaran.setText("Data Pembayaran");
        jButton_pembayaran.setMaximumSize(new java.awt.Dimension(120, 23));
        jButton_pembayaran.setMinimumSize(new java.awt.Dimension(120, 23));
        jButton_pembayaran.setPreferredSize(new java.awt.Dimension(108, 23));
        jButton_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pembayaranActionPerformed(evt);
            }
        });

        jLabel_logout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel_logout.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_logout.setText("Logout");
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_pengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_logout)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_produk, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton_pengiriman, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_pembeli, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton_pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_karyawanActionPerformed
        // TODO add your handling code here:
        DataKaryawan k = new DataKaryawan();
        k.setVisible(true);
        k.pack();
        k.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_karyawanActionPerformed

    private void jButton_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pesananActionPerformed
        // TODO add your handling code here:
        DataPesanan p = new DataPesanan();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_pesananActionPerformed

    private void jButton_pengirimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pengirimanActionPerformed
        // TODO add your handling code here:
        DataPengiriman p = new DataPengiriman();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_pengirimanActionPerformed

    private void jButton_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pembayaranActionPerformed
        // TODO add your handling code here:
        DataPembayaran p = new DataPembayaran();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_pembayaranActionPerformed

    private void jButton_pembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pembeliActionPerformed
        // TODO add your handling code here:
        DataPembeli p = new DataPembeli();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_pembeliActionPerformed

    private void jButton_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produkActionPerformed
        // TODO add your handling code here:
        DataProduk p = new DataProduk();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_produkActionPerformed

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked
        // TODO add your handling code here:
        LoginFormKaryawan l = new LoginFormKaryawan();
        l.setVisible(true);
        l.pack();
        l.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_karyawan;
    private javax.swing.JButton jButton_pembayaran;
    private javax.swing.JButton jButton_pembeli;
    private javax.swing.JButton jButton_pengiriman;
    private javax.swing.JButton jButton_pesanan;
    private javax.swing.JButton jButton_produk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
